name: build release

on:
  schedule:
    # Every tuesday at 10
    - cron: '0 10 * * 2'
  workflow_dispatch:

concurrency:
  group: release_workflow
  cancel-in-progress: true

jobs:
  check_release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions:
        write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: |
          gh variable set LAST_HIDDIFY_RELEASE --body "1223"