name: Imagin that it is build from sing-box

on:
  workflow_call:


jobs:
  executor:
    runs-on: ubuntu-latest
    steps:
      - name: BUILD TREEEEEEEEEEEEEEEEE
        run: |
          echo "Build TREE"
          tree -a